### ISSUE TITLE
unable to instsall toolchain for aarch64 

### ISSUE THREAD

**Issue by balook** [B3nac/whatislife_enum#1]
pls provide predefined  binaries for all aarch types

**Comment by B3nac** [comment]
Try these commands:

`rustup target add aarch64-linux-android --toolchain nightly`

`rustup show`

`rustup override set <nightlytoolchain>`

`cargo build --release --target=aarch64-linux-android`

Also the ndk sdk needs to be linked for the targets in .cargo/config.

It's more fun to install the toolchain, but I've provided binaries here https://github.com/B3nac/whatislife_enum/releases.

**Comment by balook** [comment]
hey man working..... mis understanding of docs

**Comment by B3nac** [comment]
No worries! Glad everything worked out.
