### ISSUE TITLE
back trace error

### ISSUE THREAD

**Issue by balook** [B3nac/whatislife_enum#3]
when running command
./whatislife_enum extenal-storage

thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', src/main.rs:176:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by B3nac** [comment]
Woops forgot to update the command docs. The path to the file needs to be provided or if running in the same directory as the file just the file name.

For example:

`adb shell /data/local/tmp/whatislife_enum external-storage /data/local/tmp/results.txt`

**Comment by balook** [comment]
adb shell /data/local/tmp/whatislife_enum apps  /data/local/tmp/results.txt
adb shell /data/local/tmp/whatislife_enum external-storage /data/local/tmp/results.txt

not showing any results

**Comment by B3nac** [comment]
Did you enumerate the file system first?

`adb shell /data/local/tmp/whatislife_enum create > results.txt` will pipe the Android filesystem to your PC. Then you can either `adb push results.txt /data/local/tmp` or run whatislife_enum create in the tmp directory and pipe to a file on the device itself. `./whatislife_enum create > results.txt`. Then if you want to run those commands from your PC it will work. The file system needs to be enumerated before the other commands will work.

**Comment by balook** [comment]
pretty hard documentation working fine

**Comment by B3nac** [comment]
Awesome! I'll update the readme.
