### ISSUE TITLE
error again

### ISSUE THREAD

**Issue by balook** [B3nac/whatislife_enum#4]
for this command adb shell /data/local/tmp/whatislife_enum filemon /data/local/tmp/results.txt /data/local/tmp/results2.txt

its giving error no such file or directory for results2.txt

Error:
comm: /data/local/tmp/results2.txt: No such file or directory

**Comment by B3nac** [comment]
Hi,

The filesystem needs to be scanned again, for example after installing or using an application to detect changes. 

1. Install a new app or create a new file.

2. Run `./whatislife_enum create > results2.txt` on the device or run it from your pc and adb push the results2.txt to the device. 

3. Lastly `adb shell /data/local/tmp/whatislife_enum filemon /data/local/tmp/results.txt /data/local/tmp/results2.txt`

**Comment by balook** [comment]
docs ........... docs .... docs ...... i think the docs are in beta stage ......
